global:
  project: experts
  image:
    registry: registry-hn02.fke.fptcloud.com
    pullPolicy: IfNotPresent
    pullSecret: fke-registry
  labels:
    app.kubernetes.io/component: be-api
deployment:
  replicaCount: 1
  envFrom:
  - name: API_URL
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: API_URL
  - name: APP_PORT
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: APP_PORT
  - name: APP_WEB_URL
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: APP_WEB_URL
  - name: AWS_SES_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: AWS_SES_ACCESS_KEY_ID
  - name: AWS_SES_REGION
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: AWS_SES_REGION
  - name: AWS_SES_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: AWS_SES_SECRET_ACCESS_KEY
  - name: DB_DATABASE
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_DATABASE
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_HOST
  - name: DB_LOGGING
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_LOGGING
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_PASSWORD
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_PORT
  - name: DB_TYPE
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_TYPE
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DB_USERNAME
  - name: DEFAULT_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: DEFAULT_USER_PASSWORD
  - name: HTTP_LOGGING
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: HTTP_LOGGING
  - name: JWT_ACCESS_EXPIRES_IN_CUSTOMER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: JWT_ACCESS_EXPIRES_IN_CUSTOMER
  - name: JWT_ACCESS_SECRET_CUSTOMER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: JWT_ACCESS_SECRET_CUSTOMER
  - name: JWT_EXPIRES_IN
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: JWT_EXPIRES_IN
  - name: JWT_REFRESH_EXPIRES_IN_CUSTOMER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: JWT_REFRESH_EXPIRES_IN_CUSTOMER
  - name: JWT_REFRESH_SECRET_CUSTOMER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: JWT_REFRESH_SECRET_CUSTOMER
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: JWT_SECRET
  - name: MAIL_DRIVER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MAIL_DRIVER
  - name: MAIL_FROM
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MAIL_FROM
  - name: MINIO_BUCKET
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET
  - name: MINIO_BUCKET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET_ACCESS_KEY
  - name: MINIO_BUCKET_END_POINT
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET_END_POINT
  - name: MINIO_BUCKET_PORT
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET_PORT
  - name: MINIO_BUCKET_REGION
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET_REGION
  - name: MINIO_BUCKET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET_SECRET_KEY
  - name: MINIO_BUCKET_SSL
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: MINIO_BUCKET_SSL
  - name: NODE_ENV
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: NODE_ENV
  - name: OTP_SIGNATURE_ENABLED
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: OTP_SIGNATURE_ENABLED
  - name: OTP_SIGNATURE_SECRET
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: OTP_SIGNATURE_SECRET
  - name: PAYMENT_CONFIG_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: PAYMENT_CONFIG_ENCRYPTION_KEY
  - name: REDIS_HOST
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: REDIS_HOST
  - name: REDIS_PORT
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: REDIS_PORT
  - name: S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: S3_ACCESS_KEY_ID
  - name: S3_BUCKET_PRIVATE
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: S3_BUCKET_PRIVATE
  - name: S3_BUCKET_PUBLIC
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: S3_BUCKET_PUBLIC
  - name: S3_REGION
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: S3_REGION
  - name: S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: S3_SECRET_ACCESS_KEY
  - name: SMTP_HOST
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: SMTP_HOST
  - name: SMTP_PASS
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: SMTP_PASS
  - name: SMTP_PORT
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: SMTP_PORT
  - name: SMTP_SECURE
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: SMTP_SECURE
  - name: SMTP_USER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: SMTP_USER
  - name: STORAGE_DRIVER
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: STORAGE_DRIVER
  - name: STOREFRONT_URL
    valueFrom:
      secretKeyRef:
        name: experts-be-env
        key: STOREFRONT_URL
  environments:
    APP_ROLE: api
    HEALTH_PORT: '0'
  containers:
  - name: api
    repository: 344af395-857e-4e68-83ea-3972784eb4cb/experts-be
    tag: dev-2-058f240
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 256Mi
    livenessHttpGet: /health-check
    readinessHttpGet: /health-check
    failureThreshold: 6
    initialDelaySeconds: 25
    ports:
    - name: http
      value: 3000
secret:
  enabled: false
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  rules:
  - host: api.experts-dev.onair.today
    paths:
    - path: /
      port: 3000
  tls:
  - secretName: api-experts-dev-onair-today-tls
    hosts:
    - api.experts-dev.onair.today
nodeSelector: {}
tolerations: []
affinity: {}
pvc:
  enabled: false
pv:
  enabled: false
