apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: experts-be-worker-dev
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 5
  destination:
    namespace: experts-dev
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  sources:
    - chart: lemon
      repoURL: https://nguyencuong382.github.io/k8s-helm-chart
      targetRevision: 1.1.4
      helm:
        releaseName: experts-be-worker
        valueFiles:
          - $values/be-worker/dev/values.yaml
    - repoURL: https://github.com/onairvn/experts-k8s-deploy.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
